name: community_garden_planner
description: Community Garden Planner - showcase app for farmers and gardeners.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  intl: ^0.18.1
  uuid: ^3.0.7
  supabase_flutter: ^2.0.0  # NEW - Supabase client for Flutter
  http: ^0.13.6              # optional for weather integration
  flutter_dotenv: ^5.1.0
  flutter_lints: ^5.0.0
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
